# Common settings

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

# Transaction executor settings

HealthMonitoringPeriod:
    settings-key: Ethereum-TransactionsExecutor-HealthMonitoringPeriod

Db:
    AzureDataConnString:
        settings-key: Ethereum-AzureDataConnString
        types:
            - AzureTableStorage
    LogsConnString:
        settings-key: Ethereum-LogsConnString
        types:
            - AzureTableStorage

# Define specific blockchain settings below, if necessary.
#
# For example:
#
# NodeUrl:
#   settings-key: Ethereum-NodeUrl
# NodeUsername:
#   settings-key: Ethereum-NodeUsername
# NodePassword:
#   settings-key: Ethereum-NodePassword